In [4]:
import nibabel as nib
import numpy as np
import os
import pathlib

base_folder = "/workspace/2024-25ab-fai3-specialisation-project-team-specifix-1/data/Masks_&_Meshes"
output_base_folder = "/workspace/2024-25ab-fai3-specialisation-project-team-specifix-1/data/soha_19_nifti_labels"

tr_label_files = os.listdir(output_base_folder)

for file in tr_label_files:

  file_name = output_base_folder +'/' + file
  # Load image

  img = nib.load(file_name)
  print("-"*100)
  print ("Patient label file: ", file)

  # Store image as a numpy array
  img_data = img.get_fdata()

  # Check array min, max and unique values for image label values
  print("Before label check")
  print(np.amin(img_data),np.amax(img_data))
  print(np.unique(img_data))

----------------------------------------------------------------------------------------------------
Patient label file:  F145.nii.gz
Before label check
0.0 13.0
[ 0.  3.  4.  7.  9. 10. 13.]
----------------------------------------------------------------------------------------------------
Patient label file:  F034.nii.gz
Before label check
0.0 13.0
[ 0.  2.  3.  4.  9. 10. 13.]
----------------------------------------------------------------------------------------------------
Patient label file:  F123.nii.gz
Before label check
0.0 13.0
[ 0.  3.  4.  7.  9. 10. 12. 13.]
----------------------------------------------------------------------------------------------------
Patient label file:  F099.nii.gz
Before label check
0.0 13.0
[ 0.  3.  4.  7. 10. 13.]
----------------------------------------------------------------------------------------------------
Patient label file:  P072.nii.gz
Before label check
0.0 13.0
[ 0.  3.  4.  5.  7. 10. 13.]
----------------------------------------

In [2]:
import nibabel as nib
import numpy as np
import os
import pathlib

base_folder = "/workspace/2024-25ab-fai3-specialisation-project-team-specifix-1/data/Masks_&_Meshes"
output_base_folder = "/workspace/2024-25ab-fai3-specialisation-project-team-specifix-1/data/labelsTr"

tr_label_files = os.listdir(output_base_folder)

for file in tr_label_files[:2]:

  file_name = output_base_folder +'/' + file
  # Load image

  img = nib.load(file_name)
  print("-"*100)
  print ("Patient label file: ", file)

  # Store image as a numpy array
  img_data = img.get_fdata()

  # Check array min, max and unique values for image label values
  print("Before label check")
  print(np.amin(img_data),np.amax(img_data))
  print(np.unique(img_data))

----------------------------------------------------------------------------------------------------
Patient label file:  F145.nii.gz
Before label check
0.0 6.0
[0. 1. 2. 3. 4. 5. 6.]
----------------------------------------------------------------------------------------------------
Patient label file:  F034.nii.gz
Before label check
0.0 9.0
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
